export const ingredients = [
  { name: 'Beurre', price: 10 },
  { name: 'Calamar', price: 5 },
  { name: 'Chocolat', price: 11 },
  { name: 'Citron', price: 5 },
  { name: 'Cote de porc', price: 8 },
  { name: 'Crabe', price: 5 },
  { name: 'Crevette', price: 5 },
  { name: 'Cuisse de volaille', price: 8 },
  { name: 'Eau', price: 3 },
  { name: 'Farine', price: 5 },
  { name: 'Fraise', price: 5 },
  { name: 'Frite', price: 5 },
  { name: 'Fromage', price: 5 },
  { name: 'Gauffre nature', price: 22 },
  { name: 'Haricot', price: 5 },
  { name: 'Homard', price: 5 },
  { name: 'Lait', price: 5 },
  { name: 'Moule', price: 5 },
  { name: 'Oeuf', price: 5 },
  { name: 'Oignon', price: 5 },
  { name: 'Orange', price: 5 },
  { name: 'Pain', price: 6 },
  { name: 'Pain a burger', price: 6 },
  { name: 'Pate', price: 15 },
  { name: 'Pate a Pizza', price: 15 },
  { name: 'Pate fraiche', price: 15 },
  { name: 'Pomme', price: 5 },
  { name: 'Pomme de Terre', price: 5 },
  { name: 'Riz', price: 5 },
  { name: 'Salade', price: 5 },
  { name: 'Saucisse de porc', price: 10 },
  { name: 'Saumon', price: 5 },
  { name: 'Semoule', price: 10 },
  { name: 'Steack hache', price: 8 },
  { name: 'Sucre', price: 7 },
  { name: 'Thon', price: 5 },
  { name: 'Tomate', price: 5 },
  { name: 'Truite', price: 5 },
  { name: 'Viande de gibier', price: 17 },
  { name: 'Saucisson', price: 11 },
  { name: 'Viande sechee', price: 11 },
]

export const recipes = [
  { name: 'Beignet de calamar', ingredients: ['Oeuf', 'Farine', 'Lait', 'Calamar'], price: 20 },
  { name: 'Boite de nuggets', ingredients: ['Cuisse de volaille', 'Farine', 'Oeuf'], price: 18 },
  { name: 'Brochette de poulet', ingredients: ['Cuisse de volaille', 'Oignon', 'Tomate'], price: 18 },
  { name: 'Bucket de poulet', ingredients: ['Cuisse de volaille', 'Farine', 'Lait', 'Oeuf'], price: 23 },
  { name: 'Cake au saumon', ingredients: ['Saumon', 'Oeuf', 'Farine', 'Lait', 'Fromage'], price: 25 },
  { name: 'Calamar farcie', ingredients: ['Calamar', 'Oignon', 'Tomate', 'Oeuf'], price: 20 },
  { name: 'Chocolat Chaud', ingredients: ['Lait', 'Chocolat'], price: 16 },
  { name: 'Cookies', ingredients: ['Chocolat', 'Farine', 'Oeuf'], price: 21 },
  { name: 'Cotes de porc legumes', ingredients: ['Cote de porc', 'Haricot', 'Pomme de Terre'], price: 18 },
  { name: 'Couscous', ingredients: ['Saucisse de porc', 'Tomate', 'Cuisse de volaille', 'Semoule'], price: 33 },
  { name: 'Crepe', ingredients: ['Farine', 'Lait', 'Sucre'], price: 17 },
  { name: 'Croque-Monsieur', ingredients: ['Pain', 'Cote de porc', 'Beurre', 'Fromage'], price: 29 },
  { name: "Dango Fruite", ingredients: ['Farine', 'Sucre', 'Fraise', 'Orange', 'Pomme'], price: 27 },
  { name: "Donut's fraise", ingredients: ['Beurre', 'Farine', 'Sucre', 'Fraise'], price: 27 },
  { name: 'Fish & chips', ingredients: ['Farine', 'Oeuf', 'Truite', 'Frite'], price: 20 },
  { name: 'Fleur aux pommes', ingredients: ['Pate', 'Pomme', 'Sucre'], price: 27 },
  { name: 'Fondant chocolat', ingredients: ['Chocolat', 'Beurre', 'Sucre', 'Farine'], price: 33 },
  { name: "Gateau d'anniversaire", ingredients: ['Beurre', 'Sucre', 'Lait', 'Fraise', 'Oeuf'], price: 32 },
  { name: "Gateau de semoule a l'orange", ingredients: ['Orange', 'Oeuf', 'Semoule', 'Beurre', 'Sucre'], price: 37 },
  { name: 'Gauffre Nature', ingredients: ['Farine', 'Oeuf', 'Lait', 'Sucre'], price: 22 },
  { name: 'Gauffre au sucre', ingredients: ['Gauffre nature', 'Sucre'], price: 29 },
  { name: 'Hachis Parmentier', ingredients: ['Pomme de Terre', 'Lait', 'Steack hache'], price: 18 },
  { name: 'Homard roti au beurre', ingredients: ['Homard', 'Beurre', 'Salade'], price: 20 },
  { name: 'Le ClassiQ', ingredients: ['Pomme de Terre', 'Saucisse de porc', 'Pomme'], price: 20 },
  { name: '3x Limonades', ingredients: ['Eau', 'Citron', 'Sucre'], price: 15 },
  { name: '3x Macarons', ingredients: ['Fraise', 'Chocolat', 'Citron', 'Oeuf'], price: 26 },
  { name: 'Mamie Steak', ingredients: ['Steack hache', 'Haricot', 'Pomme de Terre'], price: 18 },
  { name: "Mass'welsh", ingredients: ['Pain', 'Fromage', 'Steack hache', 'Cuisse de volaille'], price: 27 },
  { name: 'Milkshake chocolat', ingredients: ['Lait', 'Chocolat', 'Sucre'], price: 23 },
  { name: 'Milkshake fraise', ingredients: ['Lait', 'Fraise', 'Sucre'], price: 17 },
  { name: 'Mochi Fraise-Chocolat', ingredients: ['Farine', 'Sucre', 'Chocolat', 'Fraise'], price: 28 },
  { name: 'Moule frites', ingredients: ['Moule', 'Frite', 'Oignon'], price: 15 },
  { name: 'Mousse au Chocolat', ingredients: ['Oeuf', 'Chocolat', 'Sucre'], price: 23 },
  { name: 'Muffins au chocolat', ingredients: ['Chocolat', 'Farine', 'Lait'], price: 21 },
  { name: 'Nouilles', ingredients: ['Pate fraiche', 'Oeuf', 'Viande de gibier'], price: 37 },
  { name: 'Onigiri au crabe', ingredients: ['Riz', 'Crabe', 'Oignon'], price: 15 },
  { name: 'Paella', ingredients: ['Riz', 'Moule', 'Crevette'], price: 15 },
  { name: 'Pain perdu', ingredients: ['Pain', 'Oeuf', 'Sucre'], price: 18 },
  { name: 'Pate au Crabe', ingredients: ['Pain a burger', 'Crabe', 'Salade', 'Tomate'], price: 21 },
  { name: 'Pates au beurre', ingredients: ['Pate fraiche', 'Beurre'], price: 25 },
  { name: 'Pates bolognaise', ingredients: ['Pate fraiche', 'Tomate', 'Steack hache'], price: 28 },
  { name: 'Pates a la carbonara', ingredients: ['Pate fraiche', 'Oeuf', 'Fromage', 'Cote de porc'], price: 33 },
  { name: 'Pates au saumon', ingredients: ['Pate fraiche', 'Lait', 'Saumon'], price: 25 },
  { name: 'Pizza canibale', ingredients: ['Pate a Pizza', 'Tomate', 'Oignon', 'Steack hache', 'Saucisse de porc', 'Fromage'], price: 48 },
  { name: 'Pizza fruitee', ingredients: ['Pate a Pizza', 'Pomme', 'Orange', 'Tomate'], price: 30 },
  { name: 'Pizza jambon', ingredients: ['Pate a Pizza', 'Tomate', 'Cote de porc'], price: 28 },
  { name: 'Pizza Margherita', ingredients: ['Pate a Pizza', 'Fromage', 'Tomate'], price: 25 },
  { name: "Porc farci a l'orange", ingredients: ['Cote de porc', 'Pain', 'Orange', 'Pomme'], price: 24 },
  { name: 'Porc Chop', ingredients: ['Cote de porc', 'Tomate', 'Oignon'], price: 18 },
  { name: 'Pot au feu', ingredients: ['Pomme de Terre', 'Viande de gibier', 'Oignon'], price: 27 },
  { name: 'Poulet Basquaise', ingredients: ['Cuisse de volaille', 'Riz', 'Tomate'], price: 18 },
  { name: 'Poulet au Curry', ingredients: ['Cuisse de volaille', 'Riz', 'Lait'], price: 18 },
  { name: 'Poulet Roti', ingredients: ['Cuisse de volaille', 'Haricot', 'Pomme de Terre'], price: 18 },
  { name: 'Puree et Fishsticks', ingredients: ['Pomme de Terre', 'Truite', 'Farine', 'Lait'], price: 20 },
  { name: 'Raclette', ingredients: ['Pomme de Terre', 'Fromage', 'Saucisson', 'Viande sechee'], price: 32 },
  { name: 'Risotto au Homard', ingredients: ['Homard', 'Riz', 'Tomate', 'Beurre'], price: 25 },
  { name: 'Riz au lait', ingredients: ['Riz', 'Lait', 'Sucre', 'Oeuf'], price: 22 },
  { name: 'Salade Asterix', ingredients: ['Salade', 'Tomate', 'Fromage', 'Pain'], price: 21 },
  { name: 'Salade de crevette', ingredients: ['Salade', 'Crevette', 'Tomate'], price: 15 },
  { name: 'Salade de fruit', ingredients: ['Fraise', 'Pomme', 'Orange'], price: 15 },
  { name: 'Sandwich au thon', ingredients: ['Thon', 'Pain', 'Salade'], price: 16 },
  { name: 'Sashimi', ingredients: ['Thon', 'Saumon', 'Truite'], price: 15 },
  { name: 'Saute de porc farci', ingredients: ['Saucisse de porc', 'Cuisse de volaille', 'Oignon', 'Salade'], price: 28 },
  { name: 'Saumon riz', ingredients: ['Saumon', 'Riz', 'Salade'], price: 15 },
  { name: '3x Smoothie aux fruits', ingredients: ['Lait', 'Fraise', 'Orange', 'Pomme'], price: 20 },
  { name: 'Soupe de legumes', ingredients: ['Tomate', 'Haricot', 'Oignon'], price: 15 },
  { name: 'Soupe de poisson', ingredients: ['Tomate', 'Oignon', 'Truite'], price: 15 },
  { name: 'Steak Frites', ingredients: ['Steack hache', 'Frite', 'Salade'], price: 18 },
  { name: 'Sushis', ingredients: ['Riz', 'Thon', 'Saumon'], price: 15 },
  { name: 'Tarte au pomme', ingredients: ['Pomme', 'Oeuf', 'Farine'], price: 15 },
  { name: 'Tartelette citron', ingredients: ['Farine', 'Oeuf', 'Citron'], price: 15 },
  { name: 'Tartelette fraise', ingredients: ['Farine', 'Oeuf', 'Fraise'], price: 15 },
  { name: 'Tartiflette', ingredients: ['Fromage', 'Fromage', 'Cote de porc', 'Pomme de Terre'], price: 23 },
  { name: 'Tartine de confiture de fraise', ingredients: ['Pain', 'Beurre', 'Fraise'], price: 21 },
  { name: 'Thon riz', ingredients: ['Thon', 'Riz', 'Salade'], price: 15 },
]

export function getIngredientPrice(name) {
  return ingredients.find(i => i.name === name)?.price ?? 0
}

export function priceBadgeClass(price) {
  if (price <= 15) return 'badge-green'
  if (price <= 25) return 'badge-teal'
  if (price <= 35) return 'badge-blue'
  return 'badge-red'
}
